Implemented passing tdid to One Mobile endpoint.
indexexchange/oath-adapter pull request #8
Opened 2018-10-04 15:19 UTC by vzhukovsky

- code complete and unit tested

2018-11-01 14:25 UTC, ix-certification requested changes

2018-11-01 14:25 UTC, ix-certification commented on oath-htb.js
> +        var tdid = uid && uid.ext && uid.ext.rtiPartner;
It would be best to loop through the uids and fetch the value of the field `id` (which is adsrvr.org user ID) from the object where `"rtiPartner"="TDID".`

2018-11-02 14:26 UTC, vzhukovsky commented on oath-htb.js
> +        var tdid = uid && uid.ext && uid.ext.rtiPartner;
done

2018-11-02 19:51 UTC, ix-certification approved these changes

2018-11-09 16:46 UTC, merged